move:
  ros__parameters:
    plugins:
      - plansys2_move_bt_node
    waypoints:
      - home
      - monalisa
      - nocheestrellada
      - elgrito
      - maestro_aprendiz
      - guernica
      - la_joven_de_la_perla
      - las_meninas
      - el_3_de_mayo_de_1808
      - el_jardin_de_las_delicias
      - las_tres_gracias
      - la_rendicion_de_breda
      - el_nacimiento_de_venus
      - la_creacion_de_adan
      - la_ultima_cena
      - la_libertad_guiando_al_pueblo
      - el_hijo_del_hombre
      - american_gothic
      - la_persistencia_de_la_memoria
      - la_ronda_de_noche
      - impresion_sol_naciente
      - banistas_en_asnieres
      - saturno_devorando_a_su_hijo
      - whistlers_mother
      - la_gran_ola_de_kanagawa
      - el_beso
      - autorretrato_con_collar_de_espinas
      - el_carnaval_del_arlequin
      - nighthawks
      - retrato_de_adele_bloch_bauer_i
      - campbells_soup_cans
      - composition_viii
    waypoint_coords:
      home: [0.0, -0.1, 0.0]
      monalisa: [0.5, -1.4, 0.0]
      nocheestrellada: [0.5, -4.7, 0.0]
      elgrito: [-1.9, -4.7, 0.0]
      maestro_aprendiz: [-2.5, 6.4, 0.0]
      guernica: [-1.8, -1.4, 0.0]
      la_joven_de_la_perla: [1.2, -0.5, 0.0]
      las_meninas: [-0.8, 2.2, 0.0]
      el_3_de_mayo_de_1808: [-0.6, 2.9, 0.0]
      el_jardin_de_las_delicias: [-0.9, -0.7, 0.0]
      las_tres_gracias: [0.4, 2.6, 0.0]
      la_rendicion_de_breda: [-1.5, 1.8, 0.0]
      el_nacimiento_de_venus: [2.5, -1.2, 0.0]
      la_creacion_de_adan: [-1.8, -1.4, 0.0]
      la_ultima_cena: [2.0, 1.0, 0.0]
      la_libertad_guiando_al_pueblo: [4.0, 0.0, 0.0]
      el_hijo_del_hombre: [3.8, -0.5, 0.0]
      american_gothic: [0.5, -1.4, 0.0]
      la_persistencia_de_la_memoria: [0.0, -2.5, 0.0]
      la_ronda_de_noche: [-0.3, -1.9, 0.0]
      impresion_sol_naciente: [1.0, -3.8, 0.0]
      banistas_en_asnieres: [2.2, -2.2, 0.0]
      saturno_devorando_a_su_hijo: [-2.8, -1.0, 0.0]
      whistlers_mother: [-3.0, 0.5, 0.0]
      la_gran_ola_de_kanagawa: [3.1, -3.0, 0.0]
      el_beso: [1.5, -1.0, 0.0]
      autorretrato_con_collar_de_espinas: [0.5, -4.7, 0.0]
      el_carnaval_del_arlequin: [-2.5, 6.4, 0.0]
      nighthawks: [-0.9, -0.7, 0.0]
      retrato_de_adele_bloch_bauer_i: [3.8, -0.5, 0.0]
      campbells_soup_cans: [1.2, -0.5, 0.0]
      composition_viii: [2.0, 1.0, 0.0]
